apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.testplan.configMapName }}
  namespace: {{ .Values.job.namespace }}
data:
  stress-plan.jmx: |
{{ .Files.Get .Values.testplan.file | indent 4 }}