# .github/workflows/_dotnet-service.yml
name: _dotnet-service
on:
  workflow_call:
    inputs:
      project: { required: true, type: string }
      test:    { required: true, type: string }

jobs:
  build_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Application Code

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            Application Code/**/global.json
            Application Code/**/*.sln
            Application Code/**/*.csproj
            Application Code/**/Directory.Packages.props
            Application Code/**/packages.lock.json  # if you add them later

      - run: dotnet restore
      - run: dotnet build --no-restore "${{ inputs.project }}"
      - run: dotnet test  --logger trx --results-directory ./TestResults "${{ inputs.test }}"
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: Application Code/TestResults
